version: "3.9"

services:
    php-apache:
        image: egghdz/docker-compose-lamp-local:latest
        build:
            context: .
            args:
                http_port: ${HOST_HTTP_PORT:-8080}
        user: "${HOST_UID:-33}:${HOST_GID:-33}"
        ports:
            - "${HOST_HTTP_PORT:-80}:80"
        volumes:
            - ./www_root:/var/www/html
        depends_on:
            - mariadb
        restart: always

    mariadb:
        image: mariadb:latest
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "UTC"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: "mariadb"
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "81:80"
        volumes:
            - /sessions
        depends_on:
            - mariadb
        restart: always

volumes:
    mariadb:
